import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { Clapperboard, Play, Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { GenreType } from "@/types/global";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

async function fetchGenres(): Promise<GenreType[]> {
	const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
		headers: {
			Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
		},
	});

	const data = await res.json();
	return data.genres;
}

export default async function RootLayout({ children }: LayoutProps<"/">) {
	const genres = await fetchGenres();

	return (
		<html
			lang="en"
			className={cn(
				"h-full",
				"antialiased",
				geistSans.variable,
				geistMono.variable,
				"font-sans",
				inter.variable,
			)}>
			<body className="min-h-full flex flex-col">
				<header className="p-6 border-b flex justify-between items-center">
					<h1 className="flex items-center gap-2 text-xl">
						<Clapperboard />
						Next Movie
					</h1>
					<form className="flex gap-1 items-center">
						<Input placeholder="Search..." />
						<Button>
							<Search />
						</Button>
					</form>
				</header>
				<main className="flex">
					<aside className="p-4 border-r flex flex-col w-50 gap-1">
						<Button
							variant="outline"
							className="justify-start">
							<Link
								className="flex gap-1 items-cente"
								href={`/`}>
								<Play />
								All Gneres
							</Link>
						</Button>
						{genres?.map(genre => {
							return (
								<Button
									key={genre.id}
									variant="outline"
									className="justify-start">
									<Link
										className="flex gap-1 items-cente"
										href={`/genre/${genre.name}/${genre.id}`}>
										<Play />
										{genre.name}
									</Link>
								</Button>
							);
						})}
					</aside>
					<div className="p-4">{children}</div>
				</main>
			</body>
		</html>
	);
}
